// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa6IulD8J2RDjR5Tq3U0s7TAk2vJm_5LE',
    appId: '1:599214026957:web:48d3c4b7f6a78e09c0f984',
    messagingSenderId: '599214026957',
    projectId: 'threadproject-abd32ke',
    authDomain: 'threadproject-abd32ke.firebaseapp.com',
    storageBucket: 'threadproject-abd32ke.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQcYmyIKjgc_8Yt7a0iIuPkoeOMCsvPZQ',
    appId: '1:599214026957:android:15179a0ef77daefcc0f984',
    messagingSenderId: '599214026957',
    projectId: 'threadproject-abd32ke',
    storageBucket: 'threadproject-abd32ke.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFg_Lm7PC-svJgswEzOs0DHAYfHZ_xZqk',
    appId: '1:599214026957:ios:6fb85474804af4a3c0f984',
    messagingSenderId: '599214026957',
    projectId: 'threadproject-abd32ke',
    storageBucket: 'threadproject-abd32ke.appspot.com',
    iosBundleId: 'com.example.day22',
  );
}
