// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8PLqjszLyfRfFbcJW0u3lAQupWVGRURs',
    appId: '1:572621009361:web:39b997fac990619448f0f0',
    messagingSenderId: '572621009361',
    projectId: 'mood-tracker-5d786',
    authDomain: 'mood-tracker-5d786.firebaseapp.com',
    storageBucket: 'mood-tracker-5d786.appspot.com',
    measurementId: 'G-8FRBEVXTDF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgZZbZs2dDSOeSdQWgx49otqVRKjBCSsw',
    appId: '1:572621009361:android:4ba40a51ad05d06d48f0f0',
    messagingSenderId: '572621009361',
    projectId: 'mood-tracker-5d786',
    storageBucket: 'mood-tracker-5d786.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSOlYibquP2DdZGOEujA8DaKjXmtdofoY',
    appId: '1:572621009361:ios:2fc41415f444268848f0f0',
    messagingSenderId: '572621009361',
    projectId: 'mood-tracker-5d786',
    storageBucket: 'mood-tracker-5d786.appspot.com',
    iosBundleId: 'com.example.moodTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSOlYibquP2DdZGOEujA8DaKjXmtdofoY',
    appId: '1:572621009361:ios:9b572db1d76e750948f0f0',
    messagingSenderId: '572621009361',
    projectId: 'mood-tracker-5d786',
    storageBucket: 'mood-tracker-5d786.appspot.com',
    iosBundleId: 'com.example.moodTracker.RunnerTests',
  );
}
